In [1]:
from os import listdir
from os.path import isfile, join, exists
import pandas as pd
import io
import numpy as np
import re
import xlrd
from datetime import datetime

In [2]:
def pandas2tsv(df,path):
    base_path = "D:/Users/ldavid/Documents/Stock Combustible"
    sep = ','
    index = False
    header = True
    encoding = 'utf-8-sig'
    df.to_csv(base_path+path,
              index=index,
              sep=sep,
              header=header,
              encoding=encoding
              )
def get_fecha2(year,month):
    for i in range(len(list_of_months)):
        if i<9 and month==list_of_months[i]:
            fecha='01-'+ '0' + str(i+1) + '-' + year
            
        elif i>8 and month==list_of_months[i]:
            fecha='01-' + str(i+1) + '-' + year
                 
    return fecha

In [37]:
list_of_years=['2005']
list_of_months=['01 Enero','02 Febrero','03 Marzo','04 Abril', '05 Mayo', '06 Junio','07 Julio','08 Agosto', '09 Septiembre','10 Octubre', '11 Noviembre', '12 Diciembre']
#list_of_months=['01 Enero','02 Febrero']

In [4]:
df = pd.read_excel('D:/Users/ldavid/Documents/Stock Combustible/Pendrives con data stock/Control de Stock/2005/01 Enero'+"/"+'control stock ENERO 2005.xls',sheet_name='Stock Informado-Teórico')

In [5]:
df

,Comparación entre Stock Informado y Teórico MES DE,Unnamed: 1,Unnamed: 2,ENERO,Día,31,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,EDELNOR,NaN,CELTA,ELECTROANDINA,NaN,NORGENER,NaN,NaN,NaN
2,NaN,Carbón,Petcoke,Carbón,Carbón,Petcoke,Carbón,Petcoke,NaN,NaN
3,NaN,[ton],[ton],[ton],[ton],[ton],[ton],[ton],NaN,NaN
4,Stock Teórico calculado desde/hasta:,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,NaN,NaN
5,Consumo teórico (ENERO),20778,21642.2,32138.7,32333.1,0,21109.9,8676.89,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Stock Informado calculado desde/hasta:,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,NaN,NaN
8,Stock Disponible Calculado (1 ENERO),13276,83193,72876.4,50226.1,28416,68068.2,15290,NaN,NaN
9,Stock Calculado (31 ENERO),-7502.01,61550.8,40737.7,17893,28416,67466.3,27121.1,NaN,NaN
10,Compras Comprometidas (ENERO),39000,0,46907,123000,0,0,0,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Consumo Informado (ENERO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Stock Informado (1 ENERO),13276,83193,72876.4,50226.1,28416,68068.2,15290,NaN,NaN
14,Pérdidas Consumo (ENERO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Diferencia entre consumo Informado y Teórico,-20778,-21642.2,-32138.7,-32333.1,0,-21109.9,-8676.89,NaN,NaN
17,Diferencia entre consumo Informado y Teórico%,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Stock y Consumo de Combustible DIESEL y FO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,EDELNOR,NaN,CELTA,ELECTROANDINA,NaN,Gasatacama,AesGener,Norgener,NaN
24,NaN,Diesel,FO,Diesel,Diesel,FO,Diesel,Diesel,FO,NaN
25,NaN,[m^3],[m^3],[m^3],[m^3],[m^3],[m^3],[m^3],[m^3],NaN
26,Stock Teorico calculado desde/hasta:,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,NaN
27,Stock Disponible Calculado al 1 de ENERO,5278,4534.74,300,8827,18262,3827,1404,750,NaN
28,Consumo teórico del 1 al 30 de ENERO,44.078,73.3618,0,0,0,NaN,NaN,NaN,NaN
29,NaN,0,0,0,0,0,0,0,0,NaN
30,Stock Informado calculado desde/hasta:,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,NaN
31,Stock Disponible Informado (al 31 mayo),303.5,144.3,-,5811,9308.5,-,-,-,NaN
32,Compras comprometidas (junio),185.6,0,-,1383,0,-,-,-,NaN
33,Stock Total Disponible al 31 de ENERO,5233.92,4461.38,300,8827,18262,3827,1404,750,NaN
34,Stock Final,-4744.82,-4317.08,-,-1633,-9793.93,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Detalle Edelnor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,ARICA,IQUIQUE,NaN,ANTOFAGASTA,NaN,MANTOS BLANCOS,NaN,MEJILLONES,NaN
42,NaN,Diesel,Diesel,FO,Diesel,FO,Diesel,FO,Diesel,FO
43,NaN,[m^3],[m^3],[m^3],[m^3],[m^3],[m^3],[m^3],[m^3],[m^3]
44,Stock Teorico calculado desde/hasta:,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO,1-30 ENERO
45,Stock Disponible Calculado al 1 de ENERO,308,330,815.789,240,813.684,500,2105.26,3900,800
46,Consumo teórico del 1 al 30 de ENERO,12.5937,8.44506,19.6704,21.9726,15.6859,1.06668,38.0054,0,0
47,Stock Total Disponible al 31 de ENERO,295.406,321.555,796.119,218.027,797.998,498.933,2067.26,3900,800

In [39]:
listLines = []

def read_excel_files(folder):
    onlyfiles = [f for f in listdir(folder) if isfile(join(folder, f))]
    onlyfiles = filter(lambda x:x.endswith((".xls")), onlyfiles)
    

    data={}
    columns=['Empresa','Tipo_combustible','Stock_inicial','Stock_final','Mermas','fecha']
    df2 = pd.DataFrame(data=data, columns=columns)
    
    for excel_file in onlyfiles:
        print(excel_file)
        df = pd.read_excel(folder+"/"+excel_file,sheet_name='Stock Informado-Teórico')        
    
    
        C=df.index[df['Comparación entre Stock Informado y Teórico MES DE'] == 'Stock Final'].tolist()

            #Eldenor carbón
        df3 = pd.DataFrame({'Stock_inicial':[df.iloc[8,1]],'Stock_final':[df.iloc[9,1]],'Tipo_combustible':[df.iloc[2,1]],'Mermas':[0],'Empresa':[df.iloc[1,1]]})
        df2 = df2.append(df3)
            #Eldenor petcoke
        df3 = pd.DataFrame({'Stock_inicial':[df.iloc[8,2]],'Stock_final':[df.iloc[9,2]],'Tipo_combustible':[df.iloc[2,2]],'Mermas':[0],'Empresa':[df.iloc[1,1]]})
        df2 = df2.append(df3)
        
            #Celta carbón
        df3 = pd.DataFrame({'Stock_inicial':[df.iloc[8,3]],'Stock_final':[df.iloc[9,3]],'Tipo_combustible':[df.iloc[2,3]],'Mermas':[0],'Empresa':[df.iloc[1,3]]})
        df2 = df2.append(df3)     
        
            #Electroandina carbón
        df3 = pd.DataFrame({'Stock_inicial':[df.iloc[8,4]],'Stock_final':[df.iloc[9,4]],'Tipo_combustible':[df.iloc[2,4]],'Mermas':[0],'Empresa':[df.iloc[1,4]]})
        df2 = df2.append(df3)  
            #Electroandina petcoke
        df3 = pd.DataFrame({'Stock_inicial':[df.iloc[8,5]],'Stock_final':[df.iloc[9,5]],'Tipo_combustible':[df.iloc[2,5]],'Mermas':[0],'Empresa':[df.iloc[1,4]]})
        df2 = df2.append(df3)    
        
            #Norgener carbón
        df3 = pd.DataFrame({'Stock_inicial':[df.iloc[8,6]],'Stock_final':[df.iloc[9,6]],'Tipo_combustible':[df.iloc[2,6]],'Mermas':[0],'Empresa':[df.iloc[1,6]]})
        df2 = df2.append(df3) 
            #Norgener petcoke
        df3 = pd.DataFrame({'Stock_inicial':[df.iloc[8,7]],'Stock_final':[df.iloc[9,7]],'Tipo_combustible':[df.iloc[2,7]],'Mermas':[0],'Empresa':[df.iloc[1,6]]})
        df2 = df2.append(df3)         
        
        #---------------------------------------------------------------------------------------
        
            #Eldenor diesel
        df3 = pd.DataFrame({'Stock_inicial':[df.iloc[31,1]],'Stock_final':[df.iloc[33,1]],'Tipo_combustible':[df.iloc[24,1]],'Mermas':[0],'Empresa':[df.iloc[23,1]]})
        df2 = df2.append(df3) 
            #Eldenor oil
        df3 = pd.DataFrame({'Stock_inicial':[df.iloc[31,2]],'Stock_final':[df.iloc[33,2]],'Tipo_combustible':[df.iloc[24,2]],'Mermas':[0],'Empresa':[df.iloc[23,1]]})
        df2 = df2.append(df3)       

            #Celta diesel
        df3 = pd.DataFrame({'Stock_inicial':[df.iloc[31,3]],'Stock_final':[df.iloc[33,3]],'Tipo_combustible':[df.iloc[24,3]],'Mermas':[0],'Empresa':[df.iloc[23,3]]})
        df2 = df2.append(df3)          
        
            #ELECTROANDINA diesel
        df3 = pd.DataFrame({'Stock_inicial':[df.iloc[31,4]],'Stock_final':[df.iloc[33,4]],'Tipo_combustible':[df.iloc[24,4]],'Mermas':[0],'Empresa':[df.iloc[23,4]]})
        df2 = df2.append(df3)          
            #ELECTROANDINA oil
        df3 = pd.DataFrame({'Stock_inicial':[df.iloc[31,5]],'Stock_final':[df.iloc[33,5]],'Tipo_combustible':[df.iloc[24,5]],'Mermas':[0],'Empresa':[df.iloc[23,4]]})
        df2 = df2.append(df3) 
        
            #Gastacama diesel
        df3 = pd.DataFrame({'Stock_inicial':[df.iloc[31,6]],'Stock_final':[df.iloc[33,6]],'Tipo_combustible':[df.iloc[24,6]],'Mermas':[0],'Empresa':[df.iloc[23,6]]})
        df2 = df2.append(df3) 
        
            #Aesgener diesel
        df3 = pd.DataFrame({'Stock_inicial':[df.iloc[31,7]],'Stock_final':[df.iloc[33,7]],'Tipo_combustible':[df.iloc[24,7]],'Mermas':[0],'Empresa':[df.iloc[23,7]]})
        df2 = df2.append(df3)     
        
            #Norgener oil
        df3 = pd.DataFrame({'Stock_inicial':[df.iloc[31,8]],'Stock_final':[df.iloc[33,8]],'Tipo_combustible':[df.iloc[24,8]],'Mermas':[0],'Empresa':[df.iloc[23,8]]})
        df2 = df2.append(df3) 
        
        df2['fecha']=get_fecha2(year,month)
        listLines.append(df2)
    output = pd.concat(listLines)
    output_path = "Stock combustible 2005.csv"
    pandas2tsv(output,output_path)
    
for year in list_of_years:
    folder1 = 'D:/Users/ldavid/Documents/Stock Combustible/Pendrives con data stock/Control de Stock/'+year
    for month in list_of_months:
        folder='D:/Users/ldavid/Documents/Stock Combustible/Pendrives con data stock/Control de Stock/'+year+'/'+month
        read_excel_files(folder)

control stock ENERO 2005.xls

D:\ProgramData\Anaconda3\envs\tf\lib\site-packages\pandas\core\frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

control stock FEBRERO 2005.xls
control stock MARZO 2005.xls
control stock ABRIL 2005.xls
control stock MAYO 2005.xls
control stock JUNIO 2005.xls
control stock JULIO 2005.xls
control stock AGOSTO 2005.xls
control stock SEPTIEMBRE 2005.xls
control stock OCTUBRE 2005.xls
control stock NOVIEMBRE 2005.xls
control stock DICIEMBRE 2005.xls

In [36]:
df.iloc[23,7]

'AesGener'

In [18]:
df.iloc[C[0],1]

-4744.821993728578